### ISSUE TITLE
error in predict

### ISSUE THREAD

**Issue by hites77** [SandraCastilloPriego/CarveFungi#2]
model = tf.keras.models.load_model('selected_models/model-all')

no model-all available in zenodo, zenodo only have model_train

**Comment by SandraCastilloPriego** [comment]
I've updated the link in the Readme. Sorry for the mistake.

**Comment by hites77** [comment]
thanks, but facing issue in installation of predict (pip install predict) in ubuntu. did you know any way/alternative ?

**Comment by SandraCastilloPriego** [comment]
Hi, 
"predict" is not an available package. Sorry for the confusion. The "predict" script can be found in the "/bin/compartmentPrediction/predict.py" folder of this package. It is a python script. To import it you should change the path in the script or copy it in to the running folder (if you move it you should edit it and change the path to the models).

**Comment by hites77** [comment]
Okay, but now new error:
>>> predict("data/annotations/fasta/example.fasta","Saccharomyces_cerevisiae_s288c_sgd_nog.emapper.annotations","results")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/CarveFungi/bin/compartmentPrediction/predict.py", line 181, in predict
    train = data_training(row[0],organism_fasta_file)
  File "/home/CarveFungi/bin/compartmentPrediction/predict.py", line 43, in __init__
    self.aa, self.onehot, self.sec_features = self.get_aa_data(entry_id, path)
  File "/home/CarveFungi/bin/compartmentPrediction/predict.py", line 83, in get_aa_data
    fastafile = open(str(path) + entry_id + ".fasta", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'data/annotations/fasta/example.fastaYAL012W.fasta'

Why it is appending YAL012W.fasta to example.fasta ?

**Comment by SandraCastilloPriego** [comment]
Hi,

if you are not running the code from the original directory, you will have
to change the path of that also.

**Comment by hites77** [comment]
i am following as per the notebook instructions, the original directory was carveFungi where i run the python codes.
Where to change the path ?

**Comment by SandraCastilloPriego** [comment]
I'm a bit puzzled with the error you got. Would it be fine for you if I
check it more carefully next Monday?
Please, don't give up the tool. We will solve all the problems.

**Comment by hites77** [comment]
Ok thanks, Let me know that whether it will be suitable for building model of saccharomyces pastorianus, as it is hybrid of two different yeast species (S.cerevisae and S.eubayanus). Does this tool just add compartment and/or improve model when compared to carveme. Because I tried using carveme alone but number of reactions, metabolites, genes were less when compared to kbase generated model (kbase generate 8 compartment also). Do let me know your thoughts on this.

**Comment by SandraCastilloPriego** [comment]
We have curated the universal database of reactions. That alone may improve
the quality of the model. We are still curating it and in few weeks we well
release a better universal database of reactions.
Another step that may improve the model reconstruction is the gene
annotation. Here we use EggNog, but other gene annotation methods could be
integrated and it would remove part of the uncertainties the carveme
approach is trying to solve. Adding compartments is part of this pipeline
but it may not improve drastically the quality of the model, it makes it a
bit more realistic and also a bit more complex.

**Comment by SandraCastilloPriego** [comment]
I realized that the tutorial is in the repository is old. I will update it now. The problem is that you need the secondary structure predictions for the compartment prediction.

**Comment by hites77** [comment]
Ok I will check it and will get back to you. My server has no GPU, does it will effect the tensorflow working ?
Also, does I can directly provide eggnog output rather than running it here ?

**Comment by SandraCastilloPriego** [comment]
Hi, you don't need GPU to do the predictions.
You can provide the eggnog file. You don't need yo run it there again.
